This XML file does not appear to have any style information associated with it. The document tree is shown below.
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:tns="http://server.soap.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://server.soap.com/" name="testServiceService">
<types>
<xsd:schema version="1.0" targetNamespace="http://server.soap.com/"></xsd:schema>
</types>
<message name="soapServer">
<part name="InputArg" element="xsd:string"/>
</message>
<message name="soapServerResponse">
<part name="return" element="xsd:string"/>
</message>
<portType name="testService">
<operation name="soapServer">
<input wsam:Action="soapServer" message="tns:soapServer"/>
<output wsam:Action="http://server.soap.com/testService/soapServerResponse" message="tns:soapServerResponse"/>
</operation>
</portType>
<binding name="testServicePortBinding" type="tns:testService">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
<operation name="soapServer">
<soap:operation soapAction="soapServer"/>
<input name="soapServer">
<soap:body use="literal"/>
</input>
<output name="soapServerResponse">
<soap:body use="literal"/>
</output>
</operation>
</binding>
<service name="testServiceService">
<port name="testServicePort" binding="tns:testServicePortBinding">
<soap:address location="http://127.0.0.1:1337/testService"/>
</port>
</service>
</definitions>